# Generated by Django 3.1.5 on 2021-01-28 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_comment_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='good',
            field=models.IntegerField(default=0, verbose_name='いいね'),
        ),
    ]
